// sample generated by caster.py : https://github.com/vivekpathak/casters
// modify/adapt/copy as needed

function(doc) {

   require( "views/lib/libSlowFiboExample.js" );

   var start = new Date().getTime(); 

   var s = fibo(32); 

   var finish = new Date().getTime(); 
 
   log( "fibo is " + s + " computed in " + (finish - start) + "ms" ) ;

   emit(doc._id, doc);
}
