// sample generated by caster.py : https://github.com/vivekpathak/casters
// modify/adapt/copy as needed

function(doc) {

   var fibo = require( "views/lib/libSlowFiboExample.js" ).fibo ;

   var start = new Date().getTime(); 
   
   var n = 23; 
   var s = fibo(n); 

   var finish = new Date().getTime(); 
 
   log( "fibo(" + n + ") is " + s + " computed in " + (finish - start) + "ms" ) ;

   emit(doc._id, s);
}
