// sample generated by caster.py : https://github.com/vivekpathak/casters
// modify/adapt/copy as needed

function(doc) {
   var ExampleStatisticsCons = require( "views/lib/libExample.js" );
   var s = new ExampleStatisticsCons() ;

   for( var i = 0 ; i < 10 ; i++ ) { 
      s.addValue(Math.random()) ;
   }
   
   log( "average is " + s.getAverage() ) ;
   emit(doc._id, doc);
}
