// sample generated by caster.py : https://github.com/vivekpathak/casters
// modify/adapt/copy/rename as needed
// filenames matching *test*.js in subdirecctory tests of the view are considered tests 
// see https://developer.mozilla.org/en-US/docs/SpiderMonkey/Creating_JavaScript_tests

load("caster_harness.js") ;   
// creates fns & variables  
// fns : map() , reduce() , emit() , sum(), require(), log(), sum() 
// vars : keys , values


var doc = { 
   "_id" : "ABCD" , 
   "dummy" : "DUMMY" 
   } ;

// call the couchdb map/reduce functions as desired by the testcase  
map(doc) ;

// test work as conditions on the computed data stored in keys, values, eg: 
assertEq( keys[0] , "ABCD" ) ; 
//assertEq(2+2,5,"failed to get 5 from 2+2");

print( "passed dummy test" ) ;
