// sample generated by caster.
// see http://wiki.apache.org/couchdb/Document_Update_Validation  

function(newDoc, oldDoc, userCtx, secObj) {
  // eg: throw( {forbidden: 'detailed message'} ) ; 
  // or throw( {unauthorized: '...'} ) ;
}

